config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :boats do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index]

  get 'set_status/:id', to: 'bookings#set_status', as: 'status'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location? # do I change this to location?


  # validates :name, presence: true
  # # validates :type, presence: true
  # validates :price, presence: true
  # validates :location, presence: true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :boat
  has_many :reviews # check the names of everything

  # validates :starting_date_time, presence: true
  # validates :ending_date_time, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  # validates :rating, presence: true
  # validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :boats, dependent: :destroy
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :username, presence: true, uniqueness: :true
  # validates :password, presence: true
  # validates :email, presence: true
  # validates :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: Whitelist approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  # Devise
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :phone_number])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController

  before_action :set_boat, only: [:show, :edit, :update, :destroy]

  def index

    if params[:query].present?
      @boats = policy_scope(Boat).where("location ILIKE ?", "%#{params[:query]}%")
    else
      @boats = policy_scope(Boat).all
      # @boats = Boat.geocoded # geocoded # returns boats with coordinates
    end

    # @boats = policy_scope(Boat).all

    # @markers = @boats.map do |boat|
    #   {
    #     lat: boat.latitude,
    #     lng: boat.longitude,
    #     infoWindow: render_to_string(partial: "info_window", locals: { boat: boat })
    #   }

    # end
  end

  def new
    @boat = Boat.new
    authorize @boat
  end

  def create
    @boat = Boat.new(boat_params)
    @boat.user = current_user
    authorize @boat

    if @boat.save
      redirect_to boats_path
    else
      render :new
    end

  end

  def show

    # These lines are for the booking form
    @booking = Booking.new
    @boats = []
    @boats << @boat
    @markers = @boats.map do |boat|
      {
        lat: boat.latitude,
        lng: boat.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { boat: boat })
      }

    end
    end


  def edit
  end

  def update
    if @boat.update(boat_params)
      redirect_to boat_path(@restaurant)
    else
      render :update
    end
  end

  def destroy
    @boat.destroy
    redirect_to boats_path
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :category, :price, :location, :description, photos: [])
  end

  def set_boat
    @boat = Boat.find(params[:id])
    authorize @boat
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings_of_user = policy_scope(Booking).where(:user == current_user)

    @incomingbooking = []
    @externalbookingrequest = []

    @bookings_of_user.each do |booking|
      if booking.boat.user == current_user
        @incomingbooking << booking
      else
        @externalbookingrequest << booking
      end

    end
  end

  def create
    @boat = Boat.find(params[:boat_id])
    @booking = Booking.new(strong_booking_params)
    @booking.user = current_user
    @booking.boat = @boat
    authorize @booking

    if @booking.save
      redirect_to bookings_path(@booking)
    else
      render 'boats/show'
    end
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def edit
  end

  def set_status
    @booking = Booking.find(params[:id])
    authorize @booking
    if params[:status].present?
      @booking.status = params[:status]
      @booking.save!
    end
    redirect_to bookings_path
  end

  def strong_booking_params
    params.require(:booking).permit(:starting_date_time, :ending_date_time)

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/_info_window.html.erb
<h2><%= boat.name %></h2>
<p><%= boat.location %></p>

app/views/boats/create.html.erb
<h1>Edit a Boat</h1>

app/views/boats/edit.html.erb
<h1>Edit a boat</h1>

app/views/boats/index.html.erb
<!-- SUB NAV BAR -->
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-index">
  <ul class="sub-nav-list">
    <li class="sub-nav-list-item">
      <p>FILTER BY </p>
    </li>
    <li class="sub-nav-list-item">
      <p>CATEGORY</p>
    </li>
    <li class="sub-nav-list-item">
      <p>PRICE</p>
    </li>
    <li class="sub-nav-list-item">
      <p>PERSON</p>
    </li>
  </ul>
</div>

  <div class="container mt-5">
    <% if params[:query].present? %>
      <% if @boats.count > 1 %>
        <p class="text-right"> <%= @boats.count %> results for "<%= params[:query] %>"</p>
      <% else %>
        <p class="text-right"> <%= @boats.count %> result for "<%= params[:query] %>"</p>
      <% end %>
    <% end %>

  <div class="row border-top-cards">
    <% @boats.each do |boat| %>
    <div class="col-sm-4">
      <div class="card-boat">
        <%= link_to boat_path(boat) do %>
        <% if (boat.photos).attached? %>
          <%= cl_image_tag boat.photos.first.key, height: 300, width: 400, crop: :fill, class: "card-image" %>
        <% else %>
          <%= cl_image_tag 'download-2_buhn0o', height: 300, width: 400, crop: :fill, class: "card-image" %>
        <% end %>

        <% if policy(boat).destroy? %>
          <li class="card-delete-boat"> <%= link_to boat_path(boat), method: :delete, data: { confirm: "Are you sure?" } do %>
          <i class="fas fa-trash-alt ml-2 white-trash"></i>
          <% end %></li>
        <% end %>

        <div class="card-boat-infos">

          <div class="text-left">
            <h2><%= boat.name %></h2>
            <p class="card-boat-description"><%= boat.description %></p>
          </div >

          <div class="text-right">
            <h2 class="card-boat-pricing"><%= boat.price %> € / Day </h2>
            <%= cl_image_tag("AvatarTest_azb3ed", class: "card-boat-user avatar-bordered") %>
          </div>
          </div>

        <% end %>
      </div>
    </div>
    <% end %>
  </div>

</div>

app/views/boats/new.html.erb
  <div class="container mt-5" >

  <h1 class="mb-2">Create a new boat</h1>
    <div class="row justify-content-center">
      <div class="col-sm-4">

      <%= simple_form_for(@boat) do |f| %>
      <%= f.input :name %>
      <%= f.input :category, collection: ["SUP", "Rowboat", "Dinghy", "Water skis", "Jetski", "Surfboard", "Kitesurfing", "Bananaboat"] %>
      <%= f.input :description %>
      <%= f.input :location %>
      <%= f.input :price, as: :currency %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>

      <%= f.submit "Create boat", class: "btn btn-success mb-4" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/boats/show.html.erb
<div class="container-show">
  <div class="row">
    <div class="col-lg-5">
      <div class="card-boat-show">
        <% if @boat.photos.attached? %>
          <% @boat.photos.each do |photo| %>
            <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
        <% end %>
        <% else %>
          <%= cl_image_tag 'download-2_buhn0o', height: 300, width: 400, crop: :fill, class: "card-image" %>
        <% end %>

        <div class="card-boat-infos-show">
          <div class="card-boat-name-description">
            <h2><%= @boat.name %></h2>
            <p><%= @boat.description %></p>
          </div>
          <div class="card-boat-price-avatar">
            <p><%= @boat.price %>€/day</p>
            <%= cl_image_tag("AvatarTest_azb3ed", class: "card-boat-user avatar-bordered") %>
          </div>
        </div>
      </div>
        <div class="mt-5 mb-5 booking-form">
    <%= simple_form_for [@boat, @booking] do |f|%>
    <div>
      <%= f.input :starting_date_time %>
    </div>
    <div>
      <%= f.input :ending_date_time %>
    </div>
    <div>
      <%= f.submit "Book now", class: "btn-mint" %>
    </div>
    <% end %>
  </div>
    </div>
      <div class="col-lg-7">
        <div class="margin-card-show">
          <div id="map"
             style="width: 100%; height: 640px;"
             data-markers="<%= @markers.to_json %>"
             data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
      </div>
  </div>







</div>

app/views/bookings/_new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <h1>Create a new booking</h1>
    <div class="col-sm-8">
      <%= simple_form_for [@boat, @booking] do |f|%>
      <%= f.input :starting_date_time %>
      <%= f.input :ending_date_time %>
      <%= f.submit "Book this", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container mt-5">
  <div class="row navbar-bottom">
    <div class="col-lg-6">
      <div class="card-booking">
        <h1 class="booking-card-title">Bookings for my Boats</h1>
          <% @incomingbooking.each do |booking| %>
            <div class="row justify-content-center">
              <div class="card-in-card-user text-center">
                <h4 class="date-of-booking"><strong>@<%= booking.user.username %></strong> wants to book <%= booking.boat.name %></h4>
                <p><%= booking.starting_date_time.strftime("%d/%m/%Y %H:%M") %> - <%= booking.ending_date_time.strftime("%d/%m/%Y %H:%M") %></p>

                <% if booking.status == "pending" %>
                <% elsif booking.status == "accepted" %>
                    <div class="d-flex align-items-center justify-content-center">
                      <h5>Current Status: </h5>
                      <h5 class="accepted-banner ml-3"> <%= booking.status.capitalize %></h5>
                    </div>
                <% else %>
                    <div class="d-flex align-items-center justify-content-center">
                      <h5>Current Status: </h5>
                      <h5 class="declined-banner ml-3"> <%= booking.status.capitalize %></h5>
                    </div>
                <% end %>

                  <% if booking.status == "pending" %>
                    <div class="row mt-1">
                      <div class="col-lg-6">
                        <%= button_to 'Accept', status_path(booking), method: :get, params: {status: 'accepted'}, class: "btn btn-success" %>
                      </div>
                      <div class="col-lg-6">
                        <%= button_to 'Decline', status_path(booking), method: :get, params: {status: 'declined'}, class: "btn btn-danger" %>
                      </div>
                    </div>
                  <% end %>

              </div>
            </div>
          <% end %>
      </div>
    </div>
      <div class="col-lg-6">
        <div class="card-booking">
          <h1 class="booking-card-title">My bookings for other Boats</h1>
            <% @externalbookingrequest.each do |booking| %>
              <div class="row justify-content-center">
                <div class="card-in-card-user text-center">
                  <h4 class="date-of-booking"><strong>You</strong> want to book <%= booking.boat.name %> from <%= booking.boat.user.username %></h4>
                  <p><%= booking.starting_date_time.strftime("%d/%m/%Y %H:%M") %> - <%= booking.ending_date_time.strftime("%d/%m/%Y %H:%M") %></p>
                <% if booking.status == "pending" %>
                    <div class="d-flex align-items-center justify-content-center">
                      <h5>Current Status: </h5>
                      <h5 class="pending-banner ml-3"> <%= booking.status.capitalize %></h5>
                <% elsif booking.status == "accepted" %>
                    <div class="d-flex align-items-center justify-content-center">
                      <h5>Current Status: </h5>
                      <h5 class="accepted-banner ml-3"> <%= booking.status.capitalize %></h5>
                    </div>
                <% else %>
                    <div class="d-flex align-items-center justify-content-center">
                      <h5>Current Status: </h5>
                      <h5 class="declined-banner ml-3"> <%= booking.status.capitalize %></h5>
                    </div>
                <% end %>
                </div>
              </div>
            <% end %>
        </div>
      </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <h1>Create a new booking</h1>
    <div class="col-sm-8">
      <%= simple_form_for [@boat, @booking] do |f|%>
      <%= f.input :starting_date_time %>
      <%= f.input :ending_date_time %>
      <%= f.submit "Book this", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container mt-5">
<h1><%= @booking.boat.name %></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAPaddle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style='background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url("<%= cl_image_path('maxi-am-brunnen-_jYWndzkkVo-unsplash_hnkbt1') %>");'>
  <div class="container text-center">
    <h1>Rent small boats and watercraft from your peers!</h1>
    <%= link_to "See all boats", boats_path, class: "btn-mint m-5" %>
    <div class="row mt-4">
        <div class="col-lg-4">
          <div class="card-homepage">
            <h1> Marc_Gätcke onTheMove </h1>
            <p></p>
            <%= cl_image_tag("AvatarTest_azb3ed", class: "avatar dropdown-toggle mr-2", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <p><h2 class="quotation-marks text-left">"</h2><em>Booking the boat with Marou was nothing short of a stroll in the park. Absolutely "manifique", 10/10 would recommend to a friend. We went to one of the Great Lakes in Michigan, because the weather was extremely hot and our dog Asterix was dying beneath his thicc fur coat.</em><h2 class="quotation-marks text-right">"</h2></p>
            <p>🛥️ ⭐⭐⭐ 🛥️</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="card-homepage">
            <h1> Maxi aka Glassmaker_69 </h1>
            <p></p>
            <%= cl_image_tag("AvatarTest_azb3ed", class: "avatar dropdown-toggle mr-2", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <p><h2 class="quotation-marks text-left">"</h2><em>Renting a surf board with Francis was close to the best thing I've ever done. And the cherry on top of the cupcake: 2 hours with surf instructor Pamela. An unforgetful experience!</em><h2 class="quotation-marks text-right">"</h2></p>
            <p>🛥️ ⭐⭐⭐⭐⭐ 🛥️</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="card-homepage">
            <h1> TJ Anonymous_User13 </h1>
            <p></p>
            <%= cl_image_tag("AvatarTest_azb3ed", class: "avatar dropdown-toggle mr-2", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <p><h2 class="quotation-marks text-left">"</h2><em>We knew there would be a stressful weekend coming up with the kids. It was obvious that we would need to get the little rascals out of the house. Nothing better than spending two days at the lakehouse up in the Berkshires. And so Jim and Sam packed their bags.</em><h2 class="quotation-marks text-right">"</h2></p>
            <p>🛥️ ⭐⭐⭐⭐ 🛥️</p>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/shared/_back-to-boats.html.erb
  <%= link_to "Back to all boats", boats_path, class: "back-to-boats-btn" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="page-container">
  <div class="content-wrap">
    <div class="footer">
      <div class="footer-links">
        <a href="https://github.com/ssaunier"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="https://www.linkedin.com/in/marc-fabian-g%C3%A4tcke-222311151/"><i class="fab fa-linkedin"></i></a>
      </div>

      <div class="footer-links">
       <a href="https://contact.com/">Contact Us |</a>
       <a href="https://www.zappos.com/general-questions">FAQ</a>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= link_to root_path, class: "navbar-menu" do %>
      <h5> <i class="fas fa-bars"></i> Menu</h5>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

        <% if user_signed_in? %>
      <% if params[:controller] == "boats" && params[:action] == "index" %> <!--- so was geht?? --->
        <%= render "shared/search_bar" %>
      <% end %>

      <% if (params[:controller] == "boats" && (params[:action] == "show" || "new")) || (params[:controller] == "bookings" && params[:action] == "index") %> <!--- so was geht?? --->
          <%= render "shared/back-to-boats" %>
      <% end %>
  </div>



        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">

        <div class="align-items-center">

          <div class="align-items-center">
            <li>
              <p class="avatar-name-text"> @<%= current_user.username %> </p>
            </li>
            <li class="nav-item dropdown">
              <%= cl_image_tag("AvatarTest_azb3ed", class: "avatar dropdown-toggle mr-2", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "See my Bookings", bookings_path, class: "dropdown-item" %>
                <%= link_to "Account", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          </div>
        </div>

        <%= link_to new_boat_path, class: "nav-item-create-a-new-button" do %>
          <h5 class="nav-link-create-a-new-button">CREATE A NEW BOAT</h5>
        <% end %>
    <% else %>
        <%= link_to new_user_session_path, class: "nav-item-login" do %>
          <h5 class="nav-link-login">LOGIN</h5>
        <% end %>
    <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<div class="">
  <div class="nav-search-bar-border">
    <%= form_tag boats_path, method: :get, class: 'nav-search-bar d-flex' do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control blend-in-search-to-nav-search",
        placeholder: "Find a boat by location"
      %>
      <%= submit_tag "Search", class: "btn-mint" %>
    <% end %>
  </div>
</div>